###

GET http://localhost:3001/api/v1/welcome

###

GET http://localhost:3001/api/v1/users/4160c2d7-1efc-461c-8621-a7825cd5148c

###

POST http://localhost:3001/api/v1/login
Content-Type: application/json

{
    "username": "baffanghirlo",
    "password": "baffanghirlo_pwd"
}

###