@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1NjdhNjIzNi00YjJlLTQ0N2UtOGYyMC0zOTdkNDUyZDE0MTIiLCJhZG1pbiI6dHJ1ZSwidXNlcm5hbWUiOiJiYW5raWNoIiwiZnVsbE5hbWUiOiJCYW5raWNoIEFkbWluIiwiZW1haWwiOiJiYW5raWNoQHNvbW1lbC5pbyIsImlhdCI6MTc1MzUzNzQzOCwiZXhwIjoxNzUzNTM4MzM4fQ.knGM10KWMSpoWApZHXEQpDkmj0teK1HTiDaQ9AoB5ZU
@refresh = 

### LOGIN + TOKEN

POST http://localhost:3001/api/v1/auth/login
Content-Type: application/json

{
    "username": "bankich",
    "password": "bankich_pwd"
}

### WELCOME

GET http://localhost:3001/api/v1/welcome HTTP/1.1
Authorization: Bearer {{token}}

### GET USER BY ID

GET http://localhost:3001/api/v1/users/me HTTP/1.1
Authorization: Bearer {{token}}

### GET TASTING BY ID

GET http://localhost:3001/api/v1/tastings HTTP/1.1
Accept-Language: en
Authorization: Bearer {{token}}

### GET EXAMS

GET http://localhost:3001/api/v1/tastings/b48b94cd-9173-415e-b258-76bf3341b087/exams HTTP/1.1
Authorization: Bearer {{token}}

### POST NEW TASTING

POST http://localhost:3001/api/v1/tastings HTTP/1.1
Accept-Language: it
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "wine_category_name": "rosato",
    "sample_number": "2025-99",
    "wine_denomination": "Cerasuolo d'Abruzzo DOC, Illuminati",
    "alcohol_content": "13.0",
    "vintage": 2023,
    "wine_temperature": "16",
    "ambient_temperature": "25",
    "tasting_date": "2024-07-25T00:00:00.000Z",
    "tasting_time": "21:00",
    "tasting_location": "Art Cafè"
}

### REFRESH TOKEN

POST http://localhost:3001/api/v1/auth/refresh HTTP/1.1
Cookie: refreshToken {{refresh}}

### LOGOUT (UNSET REFRESH TOKEN COOKIE)

POST http://localhost:3001/api/v1/auth/logout HTTP/1.1
Cookie: refreshToken {{refresh}}

###