@token =
@refresh = 
@tid =

### LOGIN + TOKEN

POST http://localhost:3001/api/v1/auth/login
Content-Type: application/json

{
    "username": "bankich",
    "password": "bankich_pwd"
}

### WELCOME

GET http://localhost:3001/api/v1/welcome HTTP/1.1
Authorization: Bearer {{token}}

### GET USER BY ID

GET http://localhost:3001/api/v1/users/me HTTP/1.1
Authorization: Bearer {{token}}

### GET TASTINGS

GET http://localhost:3001/api/v1/tastings HTTP/1.1
Accept-Language: it
Authorization: Bearer {{token}}

### GET TASTING BY ID

GET http://localhost:3001/api/v1/tastings/{{tid}} HTTP/1.1
Accept-Language: it
Authorization: Bearer {{token}}

### POST NEW TASTING

POST http://localhost:3001/api/v1/tastings HTTP/1.1
Accept-Language: it
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "wine_category_name": "rosato",
    "sample_number": "2025-99",
    "wine_denomination": "Cerasuolo d'Abruzzo DOC, Illuminati",
    "alcohol_content": "13.0",
    "vintage": 2023,
    "wine_temperature": "16",
    "ambient_temperature": "25",
    "tasting_date": "2024-07-25",
    "tasting_time": "21:00",
    "tasting_location": "Art Cafè"
}

### GET EXAMS

GET http://localhost:3001/api/v1/exams/{{tid}} HTTP/1.1
Authorization: Bearer {{token}}

### POST EXAMS

POST http://localhost:3001/api/v1/exams/{{tid}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "visual_exam": {
        "limpidity": "abbastanza_limpido",
        "color_family": "rosa",
        "color_shade": "cerasuolo",
        "consistency": "fluido",
        "bubble_grain": null,
        "bubble_number": null,
        "bubble_persistence": null,
        "notes": "qualche annotazione visuale"
    },
    "olfactory_exam": {
        "intensity": "intenso",
        "complexity": "complesso",
        "quality": "abbastanza_fine",
        "aromatic": false,
        "vinous": false,
        "floral": true,
        "fruity": true,
        "fragrant": true,
        "herbaceous": false,
        "mineral": true,
        "spicy": false,
        "ethereal": false,
        "frank": false,
        "notes": "qualche annotazione olfattiva"
    },
    "taste_olfactory_exam": {
        "sugars": "secco",
        "alcohols": "poco_caldo",
        "polyalcohols": "morbido",
        "acids": "abbastanza_fresco",
        "tannins": "poco_tannico",
        "minerals": "abbastanza_sapido",
        "balance": "abbastanza_equilibrato",
        "intensity": "intenso",
        "persistence": "persistente",
        "quality": "abbastanza_fine",
        "structure": "di_corpo",
        "notes": "qualche annotazione gustativa"
    },
    "final_considerations": {
        "evolution": "pronto",
        "harmony": "abbastanza_armonico",
        "pairings": "pesce, carni rosse, formaggi",
        "notes": ""
    }
}

### POST VISUAL EXAM

POST http://localhost:3001/api/v1/exams/{{tid}}/visual HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "limpidity": "limpido",
    "color_family": "rosa",
    "color_shade": "cerasuolo",
    "consistency": "fluido",
    "bubble_grain": null,
    "bubble_number": null,
    "bubble_persistence": null,
    "notes": "qualche annotazione visuale"
}

### POST OLFACTORY EXAM

POST http://localhost:3001/api/v1/exams/{{tid}}/olfactory HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "intensity": "intenso",
    "complexity": "complesso",
    "quality": "abbastanza_fine",
    "aromatic": false,
    "vinous": false,
    "floral": true,
    "fruity": true,
    "fragrant": true,
    "herbaceous": false,
    "mineral": true,
    "spicy": false,
    "ethereal": false,
    "frank": false,
    "notes": "qualche annotazione olfattiva"
}

### POST TASTE-OLFACTORY EXAM

POST http://localhost:3001/api/v1/exams/{{tid}}/taste HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "sugars": "secco",
    "alcohols": "poco_caldo",
    "polyalcohols": "morbido",
    "acids": "abbastanza_fresco",
    "tannins": "poco_tannico",
    "minerals": "abbastanza_sapido",
    "balance": "abbastanza_equilibrato",
    "intensity": "intenso",
    "persistence": "persistente",
    "quality": "abbastanza_fine",
    "structure": "di_corpo",
    "notes": "qualche annotazione gustativa"
}

### POST FINAL-CONSIDERATIONS EXAM

POST http://localhost:3001/api/v1/exams/{{tid}}/final HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "evolution": "pronto",
    "harmony": "abbastanza_armonico",
    "pairings": "pesce, carni rosse, formaggi",
    "notes": ""
}

### REFRESH TOKEN

POST http://localhost:3001/api/v1/auth/refresh HTTP/1.1
Cookie: refreshToken {{refresh}}

### LOGOUT (UNSET REFRESH TOKEN COOKIE)

POST http://localhost:3001/api/v1/auth/logout HTTP/1.1
Cookie: refreshToken {{refresh}}

###