@PORT = 3001
@HOSTNAME = localhost
@token = 
@uid = 

### GET USER INFO

GET http://{{HOSTNAME}}:{{PORT}}/api/v1/users/me HTTP/1.1
Authorization: Bearer {{token}}

### GET USER STATS

GET http://{{HOSTNAME}}:{{PORT}}/api/v1/users/me/stats HTTP/1.1
Authorization: Bearer {{token}}

### GET COLLEAGUES

GET http://{{HOSTNAME}}:{{PORT}}/api/v1/colleagues HTTP/1.1
Authorization: Bearer {{token}}

### GET USER STATS BY ID

GET http://{{HOSTNAME}}:{{PORT}}/api/v1/users/{{uid}}/stats HTTP/1.1
Authorization: Bearer {{token}}

### POST NEW USER

POST http://{{HOSTNAME}}:{{PORT}}/api/v1/auth/signup
Content-Type: application/json

{
    "username": "riccbru",
    "email": "riccbru@sommel.io",
    "full_name": "Riccardo Bruno",
    "birthdate": "1999-11-25",
    "password": "riccbru_pwd"
}

### LOGIN + TOKEN

POST http://{{HOSTNAME}}:{{PORT}}/api/v1/auth/login
Content-Type: application/json

{
    "username": "bankich",
    "password": "bankich_pwd"
}

### REFRESH TOKEN

POST http://{{HOSTNAME}}:{{PORT}}/api/v1/auth/refresh HTTP/1.1

###