@PORT = 3001
@HOSTNAME = localhost
@token = 
@wid = 

### GET WINES

GET http://{{HOSTNAME}}:{{PORT}}/api/v1/wines HTTP/1.1
Authorization: Bearer {{token}}

### GET WINE BY ID

GET http://{{HOSTNAME}}:{{PORT}}/api/v1/wines/{{wid}} HTTP/1.1
Authorization: Bearer {{token}}

### POST NEW WINE

POST http://{{HOSTNAME}}:{{PORT}}/api/v1/wines HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "denomination": "",
    "winemaker": "",
    "vintage": 
}

### DELETE WINE BY ID

DELETE http://{{HOSTNAME}}:{{PORT}}/api/v1/wines/{{wid}} HTTP/1.1
Authorization: Bearer {{token}}

### LOGIN + TOKEN

POST http://{{HOSTNAME}}:{{PORT}}/api/v1/auth/login
Content-Type: application/json

{
    "username": "ciclarimpo",
    "password": "ciclarimpo_pwd"
}

### REFRESH TOKEN

POST http://{{HOSTNAME}}:{{PORT}}/api/v1/auth/refresh HTTP/1.1

###

