@PORT = 3001
@HOSTNAME = localhost
@token = 

@tid = 

### GET TASTINGS

GET http://{{HOSTNAME}}:{{PORT}}/api/v1/tastings HTTP/1.1
Authorization: Bearer {{token}}

### GET TASTINGS BY ID

GET http://{{HOSTNAME}}:{{PORT}}/api/v2/tastings/{{tid}} HTTP/1.1
Authorization: Bearer {{token}}

### GET EXAMS BY ID

GET http://{{HOSTNAME}}:{{PORT}}/api/v2/exams/{{tid}} HTTP/1.1
Authorization: Bearer {{token}}

### POST VISUAL EXAM

POST http://{{HOSTNAME}}:{{PORT}}/api/v2/exams/{{tid}}/visual HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "limpidity": "quite_limpid",
    "color_family": "rosé",
    "color_shade": "salmon_pink",
    "consistency": "flowing",
    "chains_number": "",
    "rise_speed": "",
    "bubble_size": "",
    "bubble_persistence": "", 
    "notes": "some visual examination note"
}
### PUT VISUAL EXAM

PUT http://{{HOSTNAME}}:{{PORT}}/api/v2/exams/{{tid}}/visual HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "limpidity": "quite_limpid",
    "color_family": "rosé",
    "color_shade": "pink_peach",
    "consistency": "oily",
    "bubble_size": "",
    "bubble_number": "",
    "bubble_persistence": "", 
    "notes": "some visual examination note"
}

### POST OLFACTORY EXAM

POST http://{{HOSTNAME}}:{{PORT}}/api/v2/exams/{{tid}}/olfactory HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "intensity": "intense",
    "complexity": "complex",
    "quality": "distinguished",
    "aromatic": false,
    "floral": false,
    "spicy": false,
    "varietal": false,
    "vegetal": false,
    "baking": false,
    "fruity": false,
    "fragrant": false,
    "empyreumatic": false,
    "notes": "some olfactory examination note"
}

### PUT OLFACTORY EXAM

PUT http://{{HOSTNAME}}:{{PORT}}/api/v2/exams/{{tid}}/olfactory HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "intensity": "intense",
    "complexity": "complex",
    "quality": "excellent",
    "aromatic": true,
    "floral": false,
    "spicy": true,
    "varietal": false,
    "vegetal": true,
    "baking": false,
    "fruity": true,
    "fragrant": false,
    "empyreumatic": true,
    "notes": "some olfactory examination note"
}

### POST TASTE-OLFACTORY EXAM

POST http://{{HOSTNAME}}:{{PORT}}/api/v2/exams/{{tid}}/taste HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "sweetness": "dry",
    "acidity": "fresh",
    "alcohols": "warm",
    "tannicity": "tannic",
    "softness": "quite_soft",
    "saltiness": "quite_tasty",
    "effervescence": "",
    "intensity": "intense",
    "structure": "full",
    "balance": "quite_balanced",
    "persistence": "persistent",
    "quality": "good",
    "notes": "some taste-olfactory examination note"
}

### PUT TASTE-OLFACTORY EXAM

PUT http://{{HOSTNAME}}:{{PORT}}/api/v2/exams/{{tid}}/taste HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "sweetness": "medium_dry",
    "acidity": "fresh",
    "alcohols": "lightly_warm",
    "tannicity": "quite_tannic",
    "softness": "quite_soft",
    "saltiness": "salty",
    "effervescence": "",
    "intensity": "quite_intense",
    "structure": "vigorous",
    "balance": "quite_balanced",
    "persistence": "quite_persistent",
    "quality": "excellent",
    "notes": "some taste-olfactory examination note"
}

### POST FINAL-CONSIDERATIONS EXAM

POST http://{{HOSTNAME}}:{{PORT}}/api/v2/exams/{{tid}}/final HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "evolutionary_state": "ready",
    "harmony": "quite_harmonious",
    "quality": "excellent",
    "pairings": "red meat, fish, cheese",
    "notes": "some final consideration note"
}

### PUT FINAL-CONSIDERATIONS EXAM

PUT http://{{HOSTNAME}}:{{PORT}}/api/v2/exams/{{tid}}/final HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "evolutionary_state": "mature",
    "harmony": "harmonious",
    "quality": "excellent",
    "pairings": "red meat, fish, cheese",
    "notes": "some final consideration note"
}

### POST EXAMS

POST http://{{HOSTNAME}}:{{PORT}}/api/v2/exams/{{tid}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "visual_exam": {
        "limpidity": "quite_limpid",
        "color_family": "rosé",
        "color_shade": "salmon_pink",
        "consistency": "flowing",
        "chains_number": "",
        "rise_speed": "",
        "bubble_size": "",
        "bubble_persistence": "",
        "notes": "some visual examination note"
    },
    "olfactory_exam": {
        "intensity": "intense",
        "complexity": "complex",
        "quality": "distinguished",
        "aromatic": true,
        "floral": false,
        "spicy": true,
        "varietal": false,
        "vegetal": true,
        "baking": false,
        "fruity": true,
        "fragrant": false,
        "empyreumatic": true,
        "notes": "some olfactory examination note"
    },
    "taste_olfactory_exam": {
        "sweetness": "dry",
        "acidity": "quite_fresh",
        "alcohols": "warm",
        "tannicity": "tenacious",
        "softness": "velvety",
        "saltiness": "tasty",
        "effervescence": "",
        "intensity": "intense",
        "structure": "full",
        "balance": "quite_balanced",
        "persistence": "persistent",
        "quality": "very_good",
        "notes": "some taste-olfactory examination note"
    },
    "final_considerations": {
        "evolutionary_state": "ready",
        "harmony": "quite_harmonious",
        "quality": "very_good",
        "pairings": "red meat, fish, cheese",
        "notes": "some final consideration note"
    }
}

### LOGIN + TOKEN

POST http://{{HOSTNAME}}:{{PORT}}/api/v1/auth/login
Content-Type: application/json

{
    "username": "bankich",
    "password": "bankich_pwd"
}

### REFRESH TOKEN

POST http://{{HOSTNAME}}:{{PORT}}/api/v1/auth/refresh HTTP/1.1

###